### ISSUE TITLE
color picker is not working 

### ISSUE THREAD

**Issue by uocxp** [maoschanz/drawing#119]
## Description

The color picker does not seem to work ! My intuitive procedure is clicking on the icon and then click some where on the  image. The color then should get marked.
![drawing](https://user-images.githubusercontent.com/8387383/69061237-0efad080-0a19-11ea-990c-0c6b40213ec2.gif)

Should i click any button to record the color or how should this work.
## System

- OS: ubuntu 18.04
- Desktop environment: GNOME Shell 3.28.4
- Package format : ppa
- App version: 0.4.8

**Comment by maoschanz** [comment]
Launch the app from a terminal, reproduce, and tell what's written in the terminal please

**Comment by uocxp** [comment]
```logs
(com.github.maoschanz.drawing:11352): Gtk-WARNING **: 16:26:46.894: Attempting to add a widget with type GtkFlowBox to a container of type GtkBox, but the widget is already inside a container of type GtkBox, please remove the widget from its existing container first.
Traceback (most recent call last):
  File "/usr/share/drawing/drawing/image.py", line 366, in on_release_on_area
    self.active_tool().on_release_on_area(event, self.surface, event_x, event_y)
TypeError: on_release_on_area() missing 1 required positional argument: 'event_y'
```

**Comment by maoschanz** [comment]
the fix should be published next week, meanwhile if you really need a color picker, with recent GTK versions there is one here:

![Capture d’écran de 2019-11-18 16-43-08](https://user-images.githubusercontent.com/19996113/69067040-ad3f6400-0a22-11ea-919e-24b1d9153c86.png)

![Capture d’écran de 2019-11-18 16-43-13](https://user-images.githubusercontent.com/19996113/69067047-b16b8180-0a22-11ea-8100-a40ecdb7d820.png)

**Comment by PlatonB** [comment]
@maoschanz The dropper button from the last screenshot is not functional. Drawing 0.6.0.

**Comment by maoschanz** [comment]
The color picker in the screenshot from the 18/11/19 is a feature of GTK 3.24, I didn't code it myself.

If this feature doesn't work for you it's either because of the package format you use, or your distro, or your DE *(the app is tested mainly as a flatpak package, on Debian Sid, with GNOME 3.36 on Xorg; in my configuration, the GTK color picker works fine)*. You should open a new issue to provide these useful informations, that are asked by the "bug report" issue template.

----

This closed issue was about the "Color picker" tool in the sidebar, which had been fixed, and still works for me.

A few details worth mentioning about the 2 possible color pickers can be found in the help manual:

>An optional *Color Picker* tool can also help you to select a color. While the color picker from within the color editor can select **a RGB color anywhere on the screen**, the *Color Picker* tool support **translucent colors but only works for pixels from the image**.

Optional tools can be activated or deactivated from the "tools" tab of the preferences window

**Comment by PlatonB** [comment]
Thank you for the clarification. Hidden Color Picker well bypasses the problem.

> A few details worth mentioning about the 2 possible color pickers can be found in the help manual:

Just in case, I will inform you that this section of the manual [can't be googleed](https://www.google.ru/search?newwindow=1&biw=1920&bih=976&ei=TqZrX4ufDtL3qwGMxa3YCw&q=%22drawing%22+%22gnome%22+%22color+picker%22&oq=%22drawing%22+%22gnome%22+%22color+picker%22&gs_lcp=CgZwc3ktYWIQAzoGCAAQBxAeOgYIABAIEB5QkXhYvaEBYPulAWgAcAB4AIABcYgBlwOSAQMzLjKYAQCgAQGgAQKqAQdnd3Mtd2l6wAEB&sclient=psy-ab&ved=0ahUKEwiL_vzShYDsAhXS-yoKHYxiC7s4ChDh1QMIDA&uact=5).

**Comment by maoschanz** [comment]
this app isn't affiliated to the GNOME foundation, and its name isn't very googleable in general (#84), so it's sadly not surprising. This is why i wrote a help manual in the first place; then i can't do anything about people looking for help on google instead ¯\\\_(ツ)\_/¯

otherwise you can try [this](https://github.com/maoschanz/drawing/search?q=color+picker) maybe
