### ISSUE TITLE
Remove comment to not translate "Paint" keyword

### ISSUE THREAD

**Issue by scootergrisen** [maoschanz/drawing#136]
I don't like how the comment say to not translate "Paint".
Why not?

    #. This is a list of keywords. "Paint" should not be translated, the others should. Don't forget the semicolons.
    #: data/com.github.maoschanz.drawing.desktop.in:12
    msgid "Paint;Sketch;Pencil;"

**Comment by maoschanz** [comment]
Because the app is a clone of Microsoft Paint, which has this name everywhere, thus users searching "paint" in their appstore should find it easily regardless of their language

Notice that it's just a list of keywords, not something proeminently shown in the UI: you're far more free in your translation than for the rest. If you think a 4th keyword can be added you can add it even if it doesn't correspond to an english one, if you want to translate "paint" you can (as long as the untranslated word stays), etc.

**Comment by scootergrisen** [comment]
The following translations does not keep the "Paint" keyword:
nl, pt_PR, tr

**Comment by maoschanz** [comment]
thanks, i fixed it
