### ISSUE TITLE
CTRL + Mouse wheel does not zoom-in or zoom-out

### ISSUE THREAD

**Issue by BoQsc** [maoschanz/drawing#183]
## Description

Just open an image, try to press `CTRL` and use `scroll the wheel` on your mouse.  
Gnome Draw doesn't zoom-in or zoom-out.

### Screencast showing GIMP vs GNOME DRAW
![Screencast from 2020-02-13 17_48_49](https://user-images.githubusercontent.com/21064622/74452421-b907be80-4e89-11ea-8e7d-7e618085cff1.gif)

## System

- Device (desktop computer/tablet/phone/...): Laptop
- OS: Ubuntu 19.10
- Desktop environment: GNOME
- Package format (flatpak, native package, snap?): snap
- App version: 0.4.7-15-g011868f86f

**Comment by maoschanz** [comment]
It's not "GNOME Draw", i'm not affiliated with the GNOME foundation 😅

Anyway, it's a feature i already implemented, it'll be released with the version 0.6.1

**Comment by Imerion** [comment]
Great to hear that feature is implemented!

I might have mentioned this before, and you might have answered. Sorry if that is the case. ;) But something I'd like to request is an option to make it so that mouse wheel zooms in and out by default, without the need for a modifier button. I personally prefer that workflow as I often need to quickly go in and out in images I work with (and then use middle-click to pan around). It's also beneficial since most other programs I use in my workflow has that behaviour by default (Blender, Godot, etc) or has an option for it (Inkscape, GIMP, etc). Thanks!

**Comment by maoschanz** [comment]
>I'd like to request is an option to make it so that mouse wheel zooms in and out by default, without the need for a modifier button.

Already done but not released yet. But it'll stay off by default because the middle click is not usable with most touchpads

The zoom controls: ![Capture d’écran de 2020-02-15 17-44-17](https://user-images.githubusercontent.com/19996113/74591766-f51e5900-501a-11ea-86c3-dfd1f8ed473f.png)

The related option: ![Capture d’écran de 2020-02-15 17-44-36](https://user-images.githubusercontent.com/19996113/74591765-f485c280-501a-11ea-9ab7-0c36b7ea84f1.png)

**Comment by Imerion** [comment]
Brilliant! Thanks a lot, I really appreciate it.
