### ISSUE TITLE
Resize the canvas by adding "handles" to the canvas

### ISSUE THREAD

**Issue by dogmax** [maoschanz/drawing#212]
## Use case

The use case is that you can resize the canvas while not having to switch a tool from the menu bar and it is easy to see how you resize the canvas. Is discoverability a word? I don't know. It's just a nice and easy way to resize a picture. Less "overhead" then you use it.

![image](https://user-images.githubusercontent.com/2283783/77668904-f036b880-6f7b-11ea-9cd3-22f007cf58ad.png)

## Suggested solution

The right handle only resizes the canvas' width. 

The bottom handle only resizes the canvas' height. 

The handle in the corner is "free moving". You can move it any way you want and it resizes the canvas accordingly. 

Maybe try this in MSPaint if you want?

The "Crop" tool is really not that intuitive. Sorry, I don't want to be harsh but it's just not easy to figure out how it works. Also, the handles are visible so it's easier to see how you resize the canvas. You don't have to dive through a menu to do it.

You only need to add those three handles. You don't need handles at the other sides/corners because the canvas is always fixed to the top-right corner of the window.

### Possible drawbacks

I'm not really sure what the drawbacks could be. Maybe make sure the handles are big enough that you can use them on touch screen?

**Comment by maoschanz** [comment]
>Is discoverability a word? I don't know.

Yes it's a word, but i think an explicit crop tool is more discoverable than tiny handles -- also i'm not sure why you speak about the menubar, the tools should be directly accessible at the left of the window

Usability is also a word, and a broader one: i prefer solutions where users can crop without having to target such small UI elements. Cropping to a specific size in pixels is also cool imo. Bigger handles are not a miraculous solution, because it would bother usability of every tool, with annoying accidental cropping. Speaking of other tools, permanent handles to crop would destroy the entire usability of the "scale" tool (this conflict is maybe more obvious if you/once you'll try the development version)

>Maybe try this in MSPaint if you want?

lol are you implying i cloned MS Paint without trying it

>You don't need handles at the other sides/corners because the canvas is always fixed to the top-right corner of the window.

This part is not true, i display the image here for technical reasons but it doesn't dismiss cases where user wants to crop the top or the left of an image 

(btw [screenshot from older MS Paint with 9 handles](https://microzoom.fr/img/57/mspaint-xp-sous-windows-7.png))

>The "Crop" tool is really not that intuitive. Sorry, I don't want to be harsh but it's just not easy to figure out how it works. Also, the handles are visible so it's easier to see how you resize the canvas.

100% exact, this has been covered by #85, where a screenshot is included since it's now almost entirely fixed

you can test this solution with the __**unstable**__ version from [that deb](https://github.com/maoschanz/drawing/files/4389847/drawing_0.5_all.deb.zip) i did a few months ago, and please tell me your feedback

**Comment by avil25** [comment]
> i'm not sure why you speak about the menubar.

Because those handles are not only used for the crop but also to increase the canvas size.
