### ISSUE TITLE
Pasting an image doesn't automatically adjust to the layer beneath it

### ISSUE THREAD

**Issue by vesterlay** [maoschanz/drawing#222]
Pasting an image which has a different resolution than the default template, after anchoring leaves white blocks on the sides or cut image. Option "New image from clipboard" resolves the issue, although I wish it could work with ctrl+v as well.

**Comment by maoschanz** [comment]
Pasting is pasting. As an user, i have already chosen a size for my canvas, and it would be absolutely unacceptable if some other unrelated operation breaks what i did. And asking users to crop the image again each time they paste is not a pertinent idea in my opinion.

>"New image from clipboard" resolves the issue

...so i'll close it

_It is marked as "duplicate" because of #184, where i disagree with the initial remarks similar to yours, but i agree with several suggestions written afterwise, mostly regarding how to display the parts of the selection outside of the canvas to improve usability_
