### ISSUE TITLE
Action to copy the image that is currently being edited to clipboard

### ISSUE THREAD

**Issue by kiraleos** [maoschanz/drawing#234]
I think a lot of people's workflows include taking screenshots, editing/annotating them and them posting them on group chats. 
Simply taking the screenshot, opening Drawing, pasting into Drawing, annotating it, copying and then pasting is much faster than having to save the image to a file, then uploading that file to the group chat.

**Comment by maoschanz** [comment]
in order to not save a single file, you can currently do it this way:

- <kbd>Ctrl</kbd>+(<kbd>Shift</kbd> for an area, or <kbd>Alt</kbd> for the current window, or nothing for the whole screen)+<kbd>Screenshot</kbd>, which is the GNOME shortcuts to copy a screenshot to the clipboard instead of saving it as a file
- right-click on the app icon → edit clipboard content (or, if the app is already running, "new image" button → "from clipboard content", which corresponds to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>v</kbd> )
- edit the image
- select all (which is in the options bar of the selection tool, or <kbd>Ctrl</kbd>+<kbd>a</kbd>)
- copy the selection (<kbd>Ctrl</kbd>+<kbd>c</kbd>)

and then paste into the browser.

If i understand correctly, your suggestion is to merge the 2 last steps in a more discoverable menu item?

**Comment by kiraleos** [comment]
Ah, I was missing the second to last part. I was used to just copying without selecting all, so that solves it. But still, a confirmation of the image being copied or the actual context menu going away would be a nice touch.

**Comment by maoschanz** [comment]
i reopen until i add this nice touch
