### ISSUE TITLE
[Text tool] RTL text appears reversed on the canvas

### ISSUE THREAD

**Issue by wgm-gh** [maoschanz/drawing#264]
## Description

See Title.

### Steps to reproduce the bug

1. Select the Text tool.
2. Click on canvas - the text input window appears.
3. Input RTL text - it appears as intended in that window, but in reverse order on the canvas.
4. Press "Insert here" - the input window closes and the text is still reversed.

## System

- Device (desktop computer/tablet/phone/...): Laptop
- OS: Linux Mint 20 Ulyana
- Desktop environment: Mate 1.24.0
- Package format (flatpak, native package, snap?): Not sure - it came with the OS straight from linuxmint.com
- App version: 0.4.13

**Comment by maoschanz** [comment]
it's already fine with 0.6.1

![Capture d’écran de 2020-10-15 19-18-23](https://user-images.githubusercontent.com/19996113/96164244-415bc900-0f1b-11eb-820d-ab0e1a25a179.png)

at least it looks fine, i can't read it but it resembles the wikipedia page i copied.

it should be fine since 0.4.14 i think, Mint is just a little late
