### ISSUE TITLE
Remember window size/state

### ISSUE THREAD

**Issue by Exalm** [maoschanz/drawing#271]
## Use case

Starting the window maximized.

## Suggested solution

Remember the last size and state (normal/maximized/fullscreen)

### Possible drawbacks

???

### Possible alternatives

???

**Comment by maoschanz** [comment]
it already remembers the state https://github.com/maoschanz/drawing/blob/a8163a34a17b1c59dde6d69b9ed738a2cd38bd53/data/com.github.maoschanz.drawing.gschema.xml#L81

it will not remember the exact size though, because as a user i prefer starting with a window shaped as a golden ratio rectangle

**Comment by maoschanz** [comment]
>### Possible drawbacks
>
>???

the main drawback is a poor UX if the last closed window had a weird shape

**Comment by Exalm** [comment]
Well, then it doesn't work.

**Comment by Exalm** [comment]
Asked again, so what they want to do is to have the default size without scrollbars with the image size they set. Right now it shows both scrollbars.

**Comment by maoschanz** [comment]
it memorizes the state when a window is closed, to test it:

1. start the app (it's not maximized)
1. maximize
1. close
1. start the app again → it's maximized

it's maybe not very obvious when someone opens tons of windows to try this feature specifically 😅 but in a normal use, it should work fine

----

to get a "default" state without scrollbars, it's possible:

- ...to memorize the state of the window as explained;
- ...or to change the size for new images in the preferences

but it isn't very pertinent in my opinion because while i have some control over the default size of the new images and over the default size of the new windows, it's a quite generic image editor so i expect most images to be existing files, or pixbufs created from the clipboard, whose sizes are probably big

An alternative, since the versions 0.6.x have zoom, would have been to set a zoom level so the image would exactly fit the initial size of the window, but i've never been able to make it work so i abandoned this feature 😐

**Comment by Exalm** [comment]
Nope, there was just one window there.

**Comment by Exalm** [comment]
From my POV: the app always opens with scrollbars, I was asked how to fix this, I said dunno and opened the issue. :)

**Comment by maoschanz** [comment]
No problem, i'm aware my personal requirement to have a golden ratio default window is pretty ridiculous, i just didn't imagine it would bother anyone
