### ISSUE TITLE
improve Debian packaging

### ISSUE THREAD

**Issue by jonassmedegaard** [maoschanz/drawing#281]
This project ships with a debian subdir - nice!

There are a few nits in that, however, and the project fails to build in a Debian-compliant package in a clean build environment.

Please consider cherry-picking the few "fix" changes at https://source.puri.sm/librem5-apps/drawing/ for improved conformance.

**Comment by maoschanz** [comment]
be careful with that directory, it exists mainly so i can test on various machines, but for now it's not used for actual packaging as far as i know (the Ubuntu PPA maintainer uses his own files, no idea about the official packages).

For example tests are disabled in `rules`, they shouldn't i suppose.

Also you should have forked from the 0.6.1 tag (and cherry pick the fix for #275 of course), or at least you should have versioned your release as `0.6.1~pureos+librem5.1`: the normal 0.6.2 is **NOT** released (its date is still in the future) nor finished. This changelog is actually my large uncommitted todo list, and i add/commit each individual line when something is done

Anyway, I know close to nothing about debian packaging, what here is for generic debian and what is specific to PureOS's CI?

**Comment by jonassmedegaard** [comment]
Multiple things here...

You are absolutely right that I did a sloppy packaging for PureOS, and ideally should have branched off at your officially released 0.6.1 tag instead of working from HEAD.  I can elaborate more on that if you like - here or elsewhere, my email is dr@jones.dk if you wanna reach me directly.

The topic of this issue is not PureOS packaging, however, but your upstream package: I suggest to cherry-pick some details from that PureOS packaging effort, because I think those changes may improve your upstream package.  All of the commits starting with "fix" are generic to Debian-based packaging, not specific to PureOS.

I have some experience with Debian packaging from maintaining [a few packages](https://qa.debian.org/developer.php?email=dr@jones.dk), and am happy to help.

**Comment by jonassmedegaard** [comment]
also, your debian directory is in quite good shape otherwise :-)
