### ISSUE TITLE
Provide realtime feedback to the user when moving the preview

### ISSUE THREAD

**Issue by alvarlagerlof** [maoschanz/drawing#318]
## Zoom preview live updating on move

I want to improve the zoom preview to move the painting on drag, instead of just updating when releasing the mouse

## Suggested solution

It should update position of the painting in mealtime when clicking and dragging on the zoom preview box. It currently only updates when releasing the mouse leading to a choppy feeling when moving the viewport.

![image](https://user-images.githubusercontent.com/14835120/103572590-16a36000-4ecd-11eb-9a9f-35ee6b86f041.png)

### Possible drawbacks

I'm not familiar with how this app renders the drawings and therefor not the performance. Therefor I do now know whether or not this will be laggy.

### Possible alternatives

None. There is only one possible behavior.

**Comment by maoschanz** [comment]
I didn't take time to code that yet because i expect people to mainly move using the touch gestures, the scrollbars, or the middle-click (although the workflow using the middle-click currently has a little bug that will be fixed in the version 0.6.5 i'll release saturday), these inputs are quicker to use and more precise

>I'm not familiar with how this app renders the drawings and therefor not the performance. Therefor I do not know whether or not this will be laggy.

The performance is bad when the picture is too big, but then it's bad in general and not only regarding the preview. I suppose your suggestion would make it slightly worse? But i don't expect people to open the preview very often so it's not critical

>None. There is only one possible behaviour.

there are many possible behaviours, and if i implement a reaction to the mouse motion event, it would move the light blue overlay in real time, but the image will not move in real time with it: i prefer a "choppy" minor feature rather than a chaotic rendering where even the tiniest mouse movements could move the image of hundreds of pixels, spawning hostile strobe flashes

*Side note for myself when i'll do it: change the pointer to a hand*

**Comment by alvarlagerlof** [comment]
> expect people to mainly move using the touch gestures
There can't be many people on touch though? Gnome phones and touchscreen laptops has got to make up a small minority of users.

>  the scrollbars
That's very slow and inconvenient

>  or the middle-click
I did not know that was possible. This solves my issue.  

>  prefer a "choppy" minor feature rather than a chaotic rendering where even the tiniest mouse movements could move the image of hundreds of pixels, spawning hostile strobe flashes

I completely disagree with this. I would prefer it to move both the preview and the viewport as quickly and as often as possible. It's what I'd expect from other software. Currently, it feels a bit like the app has crashed when I move it. Guess everyone is different.

**Comment by maoschanz** [comment]
>There can't be many people on touch though? Gnome phones and touchscreen laptops has got to make up a small minority of users.

i was thinking of regular laptops with a touchpad (middle-clicking can be pretty hard with them, but "scrolling" in any direction with 2 fingers is possible), i've never tested the app on a touchscreen yet

**Comment by alvarlagerlof** [comment]
> i was thinking of regular laptops with a touchpad (middle-clicking can be pretty hard with them, but "scrolling" in any direction with 2 fingers is possible)

Ah, that's good.
