### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by hmsjy2017** [maoschanz/drawing#358]
## Description
I noticed there was an icon in the menu, but not in the taskbar.

![0CFD9FC5-4C3A-4454-A279-F3198FA62D97](https://user-images.githubusercontent.com/42692274/113890487-c81c9f00-97f6-11eb-814a-71be667186c4.png)

### Steps to reproduce the bug

1. Install Drawing on Raspberry Pi

## System

- Device (desktop computer/tablet/phone/...): Raspberry Pi 4B
- OS: Raspbian Buster armhf
- Desktop environment: PIXEL
- Package format (flatpak, native package, snap?): native package
- App version:0.6.5

**Comment by maoschanz** [comment]
thanks for reporting, i'm not sure why you have the native package with version 0.6.5 on Raspian Buster (Raspian testing has 0.6.4, Raspian stable with backports enabled has 0.4.13, and Raspian Buster shouldn't have the package at all). I couldn't install the flatpak version on raspian for PC so i reproduced the problem in a normal debian buster VM

anyway the problem is that PIXEL is a variation of LXDE, which is so ancient it doesn't group windows by app name:

- this https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-icon-name has to be used on all possible windows (maybe i should only care about the 2 first kinds?)
  - [ ] app windows
  - [ ] preferences
  - [ ] about
  - [ ] shortcuts
  - [ ] the print dialog
- [ ] LXDE and LXQt should have an 'mtc' layout by default instead of an 'hg' one

**Comment by hmsjy2017** [comment]
It can be found in the PPA.
![3445FA04-484C-43D9-91E6-EBD0C71BA76B](https://user-images.githubusercontent.com/42692274/114041368-16917280-98b7-11eb-80ae-1c8eb3fd9651.png)
> this https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-icon-name has to be used on all possible windows (maybe i should only care about the 2 first kinds?)

I think it should be used on all possible windows

**Comment by maoschanz** [comment]
[drawing_0.7.2_all.zip](https://github.com/maoschanz/drawing/files/6290737/drawing_0.7.2_all.zip)

don't install this it's just for my tests
