### ISSUE TITLE
Pasting a screenshot results in it being cropped

### ISSUE THREAD

**Issue by Sentero-esp12** [maoschanz/drawing#417]
## Description

I have a 1920x1080 screen. If I do PrintScreen and then paste the screenshot into the program, it first displays fine. When I choose another tool, like pencil, it gets cropped. 
It should instead automatically detect that it's a screenshot and adjust the width and height of the working area.

## System
Linux Mint 20.2

- Device (desktop computer/tablet/phone/...): Desktop
- OS: Linux Mint 20.2
- Desktop environment: Cinnamon
- Package format: native package
- App version: 0.8.0

**Comment by Sentero-esp12** [comment]
P.S. I've figured out another way: just clicking file -> New from screenshot. Closing, unless someone else thinks it's still relevant

**Comment by maoschanz** [comment]
You may also right-click on the app icon and select the corresponding item, to launch the app directly with the content of the clipboard, no other step required. (#185)

I also recommend to use shift+printscreen *(or ctrl+shift+printscreen depending on the environment)* to define the area to screenshot before even editing, and avoid the step of cropping non-essential or personal information

----

An other option is to have a bigger default new canvas, which can be set in the preferences, so pasting it would fit. Or to zoom out and expand the blank canvas with the "crop" tool before using the selection tool to paste your screenshot.
 
Because it's not about "choosing another tool like pencil", it's about how to use the *selection* tool: when you paste something in an existing canvas (which is blank here, but still), it's selected so it can be moved around, resized, rotated, etc. until you deselect it. It's why you can see a light blue overlay on the pasted area, as well as a dotted line around it, have the related menu when you right-click on it, and have a short explanation about it in the window title

Even if you don't need to use an other tool, you **have to** deselect your selection anyway, because what will be saved is the state of the canvas (where you haven't applied anything yet if the selection is still floating around).

----

When you'll get the update to version 0.8.3 you will have an item in the selection's right-click menu to "expand the canvas to fit the selection" or something like this i don't remember how i phrase it (#332), and a visual indication of the limit of the canvas underneath (#184) which should make this a little more intuitive
