### ISSUE TITLE
Remove the vertical space between tools

### ISSUE THREAD

**Issue by vanillajonathan** [maoschanz/drawing#441]
Remove the vertical space between tools, this would make it easier to keep track of all tools at a glance, make them ore grouped, and more easier to switch between.

![image](https://user-images.githubusercontent.com/10222521/139714473-80f07938-1b19-4291-a5c0-e539fa16219c.png)

## Proposal
![image](https://user-images.githubusercontent.com/10222521/139715318-3f4c9f19-e625-41cc-99db-123273a7c516.png)

## System
- Device: Desktop
- OS: Ubuntu
- Desktop environment: GNOME
- Package format: Flatpak
- App version: 0.8.3

**Comment by maoschanz** [comment]
I don't think that compressing many clickable items in a tiny area is a pertinent use of the available space: I notice that in your proposal, you forgot to include the big weird empty space that would then be under the tools.

The current harmonious spacing is the behavior of a Gtk.Flowbox, which is the only elegant and efficient way to show the tools on 1 to 4 columns dynamically depending on the available height: *you* may have spacing, but not everyone has fancy displays, not everyone use the app maximized, and not everyone stay with the minimal set of tools. Even in full-screen mode, i have 2 columns, and the first one is made of tightly packed icons.

So it is necessary, sorry but i will not break the UX for normally-sized screens.

Also, I assume that any user with such a big display could either:
- turn on HiDPI
- use the "bigger icons" option
- have more than enough horizontal space to display the labels next to the icons (it packs them at the top of the column, which would be unusable on smaller devices)

**Comment by vanillajonathan** [comment]
I don't have some super large display, it's just a normal screen at the very normal screen resolution 1920x1200 which is probably the most common screen resolution.

Yes, there would be some empty space below the tools, but I don't think it would be weird. It would be like in other popular software like GIMP, Photoshop and MS Paint, etc.

Gtk.Flowbox sounds like the right widget choice. Maybe there is a way to configure it differently.

**Comment by maoschanz** [comment]
In 2021, the most common screen resolutions are 1920×1080 and 1366×768 (which has always been mine since my first computer: as far as i know it's the standard for non-HiDPI laptops). 

>Maybe there is a way to configure it differently

...and in my opinion these ways look ugly on my display.

Concerning the "more easier to switch between" remark, it's a mouse-centric reasoning: travelling a few millimetres with your eyes and your mouse isn't "hard", it's just slightly longer to do; but targeting a precise button among a crowded group using a touchpad or a touchpad *is* actually hard.

I would agree, however, that the click target should be wider in your situation (a mouse click happening in an empty space should trigger the closest button), and this would benefit both mouse and touch devices users

----

Meanwhile, I think that the existing "bigger icons" option would really improve your "keep track of all tools at a glance" issue, it makes them stand out.

The following screenshots (all additional tools enabled or not) are from my work's desktop computer (1920×1080) with this option enabled, and while there are empty spaces in both, they don't look visually or ergonomically weird at all

![Capture d’écran de 2021-11-02 12-13-18](https://user-images.githubusercontent.com/19996113/139836370-f8263143-dbf4-4adc-8428-88907cef8552.png)

![Capture d’écran de 2021-11-02 12-16-12](https://user-images.githubusercontent.com/19996113/139836739-fa59a6d6-f303-4646-afdb-a14d5e3e73a1.png)

**Comment by vanillajonathan** [comment]
The bigger icons are also more useful for touch.

Keep in mind that most users will likely use the default settings which does not have all the tools enabled.

**Comment by maoschanz** [comment]
>The bigger icons are also more useful for touch.

No, the size of the buttons doesn't change (maybe 1 or 2px at most depending on the theme), it's only changing the icon within the button:
it helps visually, when the user has eyesight problems or when the display is huge but HiDPI isn't enabled, but it does nothing to the empty spaces

**Comment by vanillajonathan** [comment]
Oh, it would be good if the size of the button itself big enough to prevent touching the wrong buttons in case the application would be used with a touchscreen.

https://developer.gnome.org/hig/guidelines/pointer-touch.html

> Click targets should be large enough to be comfortably used with different pointing devices and physical abilities.

**Comment by maoschanz** [comment]
>I would agree, however, that the click target should be wider in your situation (a mouse click happening in an empty space should trigger the closest button), and this would benefit both mouse and touch devices users

in the end i just removed the buttons lol

![Capture d’écran de 2021-11-13 05-35-29](https://user-images.githubusercontent.com/19996113/141648054-5eb57cb1-c87b-4fa8-920a-6cb14ef427cc.png)

**Comment by vanillajonathan** [comment]
> I would agree, however, that the click target should be wider in your situation (a mouse click happening in an empty space should trigger the closest button), and this would benefit both mouse and touch devices users

That could lead to large empty spaces far away from an icon that is clickable, it makes it rather awkward. I don't think that is a common UI pattern. You might want to look into what other software does and try something common and similar that looks, feels and behaves as users expect it to and doesn't surprise users.

Most other software seems to group buttons without spacing in between them and leave an empty space after the last button.

**Comment by maoschanz** [comment]
>it makes it rather awkward.

No it doesn't

**Comment by vanillajonathan** [comment]
Larger touch targets are good and not uncommon, but good to a certain extent. At some point the touch targets could become too big, for example on a big screen maybe.
