### ISSUE TITLE
Dark theme doesn't work

### ISSUE THREAD

**Issue by adriankwiat** [maoschanz/drawing#467]
## Description
Enabling 'Prefer dark theme variant' option doesn't change anything, app is still in light theme

![image](https://user-images.githubusercontent.com/36125672/147688143-47af1180-bf6e-4dc2-8521-7d3467098879.png)

## System

- Device (desktop computer/tablet/phone/...): 
- OS: Linux Mint 20.2
- Desktop environment: Cinnamon (with theme CBlack)
- Package format: flatpak
- App version: 0.8.5

**Comment by maoschanz** [comment]
does the expected dark variant (CBlack-Dark i suppose?) work in other apps with a similar setting available?

**Comment by adriankwiat** [comment]
This theme doesn't have any variants, it is dark only.
Similar setting has Xed editor and it does nothing too, but there dark theme is used always

**Comment by maoschanz** [comment]
ok i see, your problem is that your themes are installed for the native apps, but not for the flatpak apps. In its flatpak sandbox, Drawing can't access most files on the disk (unless you explicitely click on "Open" of course), which is a cool security feature, but it means Drawing can't see the themes installed for the native apps

The developer of CBlack has never uploaded their work to flathub so you probably can't install it "correctly" at all, and the app decided to use the fallback look of any app not finding the theme it should use

A workaround is to install Flatseal and edit the permissions of Drawing: 
![image](https://user-images.githubusercontent.com/19996113/147690462-7fb4d686-930a-4f7f-93d7-e2a14b990d64.png)
![Capture d’écran de 2021-12-29 19-01-05](https://user-images.githubusercontent.com/19996113/147690770-d3d25417-0567-4131-8a94-5ae44b4a0728.png)

if your theme is installed system-wide the switch is the `host` one, and if the theme is installed in some deprecated user-wide hidden directory, then `home` will be enough

**Comment by maoschanz** [comment]
does this fix work for you?

**Comment by adriankwiat** [comment]
Yes, it works
