### ISSUE TITLE
Pixel Art: deeper zoom, sharper rendering, more precise tools...

### ISSUE THREAD

**Issue by youssefsahli** [maoschanz/drawing#475]
Is there a way to add pixel art support?

That would include zoom > 400% and disabling the filters of the canvas

**Comment by maoschanz** [comment]
what filters?

**Comment by youssefsahli** [comment]
The linear filter used when drawing. a 32x32 pixel canvas will be blurred when you should see crisp pixels

**Comment by maoschanz** [comment]
Ok, so you want crisp pixels, the feature request is "displaying crisp pixels".

Please don't assume things about how the code works when you request a feature, it's confusing: the blurry effect is the default scaled-up surface rendering of the cairo library, i have nothing to do with it and there is no filter under my control as far as i know. Ironically the fix will likely be to render differently in order to be able to *add* a filter.
