### ISSUE TITLE
Not respecting Tool Size text box during Ctrl + A

### ISSUE THREAD

**Issue by martin-desktops** [maoschanz/drawing#478]
## Description

It's not possible to use Ctrl + A key combination inside tool size text boxes

### Steps to reproduce the bug

1. Select "Pencil" tool
2. Focus on Tool Size text box
3. Use CTRL + A key combination

## System

- Device (desktop computer/tablet/phone/...): Desktop computer
- OS: Ubuntu 21.10
- Desktop environment: Gnome 40.4
- Package format: Flatpak
- App version: 0.8.5

https://user-images.githubusercontent.com/64419373/150994045-c9d53bd2-d5dc-47a3-a92e-b2fc46cc4875.mp4

**Comment by maoschanz** [comment]
i would have never expected anyone to select the size like that, instead of erasing this number normally with the keyboard: it's like 1 or 2 digits, so it's not even an additional effort compared to <kbd>ctrl</kbd><kbd>a</kbd>. But of course, since you bring the mouse here to single-click anyway, the easiest "fix" would be to simply double-click

<kbd>ctrl</kbd><kbd>a</kbd> is "select all", it's a 100% intentional and documented feature, not a bug.

i will not remove this very standard keyboard shortcut in order to accommodate a marginal use case, sorry.
