### ISSUE TITLE
[ Feature Request ] Sense of pressure when working with graphic tablets.

### ISSUE THREAD

**Issue by d33kshant** [maoschanz/drawing#489]
## Requested feature
While using any graphic tablet amount of pressure affect the brush radius (and opacity if user wants).

### Possible drawbacks
Extra use of system resource

### Possible alternatives
using krita or any other tools that support pressure sense

## Use case
To make organic sketches and drawing
To create better base/wireframes

**Comment by maoschanz** [comment]
Is there an issue with the existing pressure-sensitive "Brush" tool?

**Comment by d33kshant** [comment]
I can't see any brush tool.
I am using popos 21.04 LTS and I've installed drawing with apt package manger. The pressure sensetive works fine when i test it in the settings.

![Screenshot](https://i.imgur.com/qdU2Lsb.png)

**Comment by maoschanz** [comment]
i don't know anything about Pop OS, the version of the app is in the "about" dialog window of the app

The "brush" tool is available since Drawing 0.8.0, but because of the drawback you mentionned in your request, it's an optional tool that you may choose to enable in the app preferences

![Capture d’écran de 2022-02-22 12-22-59](https://user-images.githubusercontent.com/19996113/155122625-e6dd2fe9-43f6-4879-8afc-45664432e48d.png)

But it's quite basic, for example you can see the transition between each segment having a different width:

![Capture d’écran de 2022-02-22 12-29-29](https://user-images.githubusercontent.com/19996113/155123799-d4440c3d-6418-49c3-9cf0-c66e39a5fe58.png)

It's especially visible if you use it with a mouse like i just did, but i guess it's not your case

I plan to add more options to that tool (#116 ) but it's not a priority for now

**Comment by maoschanz** [comment]
if your Pop OS release doesn't have Drawing 0.8.0, you can install the app using Flatpak instead

**Comment by d33kshant** [comment]
Thank you so much, Reinstalling the app from flathub and enabling brush from the prefrences fixed this issue. the version that I was using earlier was 0.6 which was from apt. i should've checked it earlier, sorry for this inconvenience 😅
