### ISSUE TITLE
Release for elementary AppCenter?

### ISSUE THREAD

**Issue by cassidyjames** [maoschanz/drawing#5]
It could be an interesting way to get more users and also potentially bring in some funds if you hook it up with Stripe.

![image](https://user-images.githubusercontent.com/611168/51875275-86902f80-2321-11e9-9371-c04053eefb8f.png)

**Comment by maoschanz** [comment]
First i'll need to finish it 😅 the history and a ton of other things are still broken.

However the UI doesn't look very great here, maybe i should try to do an alternative headerbar with more "pantheon-ish" icons

**Comment by maoschanz** [comment]
(oh no, i see you forked it, it means you're probably looking into the horrible spaghetti code full of `#XXX` 😢 don't judge me please)

**Comment by cassidyjames** [comment]
@maoschanz I didn't look at any actual code, don't worry! Was just poking at the RDNN stuff that I believe would be required for AppCenter. Regarding icons, I'm happy to poke at that as well. We typically use full-size, large-toolbar size icons in elementary apps.

**Comment by maoschanz** [comment]
So the default GNOME headerbar is now less ugly
![capture d ecran de 2019-02-02 15-43-59](https://user-images.githubusercontent.com/19996113/52165520-3f7bb300-2702-11e9-82ce-6d42e7104333.png)

But the only way i found to have buttons looking good with eOS here is to use an old-style toolbar 🙁
![capture d ecran de 2019-02-02 15-44-39](https://user-images.githubusercontent.com/19996113/52165519-3ee31c80-2702-11e9-8ee5-a5d6f421ad52.png)

Since it seems that you don't use UI files, the secret of eOS buttons is probably somewhere in a .vala file, can i have a hint? 😅

**Comment by maoschanz** [comment]
![capture d ecran de 2019-02-04 14-48-55](https://user-images.githubusercontent.com/19996113/52212520-ff950700-288c-11e9-83d0-b50895fed56b.png)

probably not the right way to do it, but fine enough

**Comment by cassidyjames** [comment]
@maoschanz we use LARGE-sized icons, and if there's an outline on the buttons, you can add the GTK style constant for flat buttons, like I did in this diff:

https://github.com/Alecaddd/Akira/pull/61/files#diff-e457c4675df228a3633f6757bea7ce6dR22

**Comment by maoschanz** [comment]
i still don't like the name, but meanwhile i've added a meson option to build it using the rdnn as the name of the binary
