### ISSUE TITLE
Simplify preview window

### ISSUE THREAD

**Issue by alex285** [maoschanz/drawing#54]
I believe all those controls take unnecessary space, without any real functionality

1. The arrows on red circles, aren't really needed. You can move the preview area, either with mouse, or touch (Gesture)

2. The zoom controls on blue circle (that isn't a circle) is redundant since the slider does the job perfectly

3. Fit on screen (i guess thats the square, b/c doesn't work) would be better if it was outside the previewer, somewhere on main window

![Screenshot from 2019-06-22 23-57-55](https://user-images.githubusercontent.com/11244308/59968874-13928a00-954a-11e9-964c-f1e0abda7374.png)

**Comment by maoschanz** [comment]
See #49: it's complex because you turned on the `devel-only` setting. With 0.4 you should only have arrows, with 0.6 you will only have zoom controls

The slider is cool because it shows the current value and gives precise control, but i'm not sure it's as usable as the buttons, anyway you will probably control that with ctrl+scroll, not with the slider

**Comment by alex285** [comment]
Oh, you have removed the "experimental" from the UI, and probably the flag was there from a previous installation :/

About the slider, personally I prefer it a million times more than buttons! Besides in all graphics programs we use sliders, and not buttons. Basically there is this thing (on professional apps), that we can slide even when there are buttons, with press-down. Point is that sliders work better :)
