### ISSUE TITLE
undo waits a long time to respond

### ISSUE THREAD

**Issue by vinkenvvt1** [maoschanz/drawing#574]
When I click undo, it takes a long time to respond. Can you fix this problem, many thanks.

**Comment by maoschanz** [comment]
It's good practice to check for existing reports before creating a new one. It's also good practice to fill the information asked by the template i took time to write, instead of erasing it.

The problem has been reported multiple times, and it's slowly being fixed: if you use the last version (i can't tell, you dismissed the issue template) you can already improve the time by saving what you're doing on a regular basis

**Comment by vinkenvvt1** [comment]
> It's good practice to check for existing reports before creating a new one. It's also good practice to fill the information asked by the template i took time to write, instead of erasing it.
> 
> The problem has been reported multiple times, and it's slowly being fixed: if you use a recent version (i can't tell, you dismissed the issue template) you can already improve the time by saving what you're doing on a regular basis

I love this program very much, keep going. I love you.

**Comment by maoschanz** [comment]
thanks 😅
