### ISSUE TITLE
Basic features

### ISSUE THREAD

**Issue by gudeh** [maoschanz/drawing#617]

**Comment by maoschanz** [comment]
>I am sorry but I have to say, this is the worst image handling software I ever used. It is sad because I really enjoy linux mint.

well, it didn't meet your expectations, but i initially created it because "gnome-paint" was the worst image handling software I ever used 😅

>I wish I could simply paste an image and save, but no, I have to resize the window and everything.

i guess you mean resizing the canvas? you have several options (i'm not sure you have all of them, depending on the version you're using: mint shipped my app since its extremely early stages!)

- you can treat the image in the clipboard as a new image. It's probably what you want to do: right-click on the app icon > "edit image in the clipboard"
- if the app is already open, *File > New image from clipboard*, or if you're using the app in a gnome environment it's *New > New image from clipboard*
- you can also stay on the poorly sized canvas, but resize it after you pasted the selection: right-click on the selection > more options > resize image to fit selection
- you can also replace the entire canvas with the selection: right-click on the selection > more options > define as current image

again it depends on your version of the app, it's more intuitive in the recent ones. Maybe you deleted the text of your comment when you found the other issues opened here?

>I wish I could select a region to crop, like: select, right click and crop, but no, lets do it all the hard way.

i'm unsure what you mean by "crop" here:

- if you want to crop the content of the selection, it's right-click > crop
- if you want to crop the image so only the selection is left, it's right-click on the selection > more options > define as current image

>After selecting the region to crop I have to select the green button, waste of time, not intuitive, every time I forget to click the damn button I lose my changes and have to do it again.

duplicate with #357 but it's a legit critique, since what i implemented in #357 hasn't been released yet

>I suggest installing windows, checking how PAINT works and try to mimic what they do, simple is better.

Paint isn't touch-friendly, and Paint isn't bound by the technical limitations of the libraries i used for this

Also, i kinda don't care about brushes or cookie-cutter shapes or whatever was their focus

>Seems to me developers are trying to be different and failing miserably. Sorry if my comments seem harsh, but I am frustrated and this software really needs to change.

i made this almost alone, as a student who wanted to edit screenshots without opening the entire GIMP suite: if you understand the app it's cool for you i'm very happy to help, but if you don't then open GIMP 🤷
